# Generated by Django 3.2.14 on 2022-07-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نام خواننده')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Audios_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نام آهنگ')),
                ('src', models.TextField(default='none')),
                ('img', models.ImageField(default=None, upload_to='')),
                ('view', models.IntegerField(default=10, verbose_name='تعداد نمایش')),
                ('time', models.DateTimeField()),
                ('num', models.IntegerField(default=1)),
                ('category', models.ManyToManyField(to='audios.Category')),
            ],
        ),
    ]
