# Generated by Django 3.2.14 on 2022-07-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audios_file',
            name='num',
        ),
        migrations.AddField(
            model_name='audios_file',
            name='Singer',
            field=models.ManyToManyField(to='audios.Singer'),
        ),
    ]
