# Generated by Django 3.2.14 on 2022-07-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_auto_20220715_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios_file',
            name='img',
            field=models.ImageField(default=None, upload_to='photos/'),
        ),
    ]
